name: of_ramadan
description: Lessons of Ramadan

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  path_provider: ^2.1.5
  sqflite: ^2.4.2
  path: ^1.9.1
  flutter_html: ^3.0.0-beta.2
  share_plus: ^11.0.0
  clipboard: ^2.0.2
  page_view_dot_indicator: ^2.3.0
  shared_preferences: ^2.5.3
  flutter_slidable: ^4.0.0
  provider: ^6.1.5
  flutter_material_color_picker: ^1.2.0
  hive_flutter: ^2.0.0-dev
  wakelock_plus: ^1.3.2
  html: ^0.15.6
  responsive_builder: ^0.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/databases/
    - assets/fonts/

  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/gilroy_medium.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat_medium.ttf
    - family: PT Sans
      fonts:
        - asset: assets/fonts/pt_sans_regular.ttf
